**Problem 1**

Import Numpy as np

In [1]:

import numpy as np

**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [2]:
arry = np.array([0,1,2,3,4,5,6,7,8,9])
arry1 = np.array(range(10))

print(arry)
print(arry1)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


**Problem 3**

Create a 3×3 numpy array of all True’s.

In [7]:
arrTrue = np.array([[True,True,True],
                    [True,True,True],
                    [True,True,True]] )
print(arrTrue)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


**Problem 4**

Extract all odd numbers from arr.

In [55]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
new_arr= [i for i in arr if i%2==1]

new_arr1=np.where(arr %2 ==1)[0]
b= arr[arr%2 !=0]


print(new_arr)
print(new_arr1)
print(b)


[1, 3, 5, 7, 9]
[1 3 5 7 9]
[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [32]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2 ==1] = -1

print(arr)




[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [33]:
arr = np.arange(10)
print(np.reshape(arr,(2,5)))


[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [40]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.vstack((a,b)))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


**Problem 8**

Stack the arrays a and b horizontally.

In [39]:
print(np.hstack((a,b)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


**Problem 9**

Get the common items between a and b.

In [42]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c= np.intersect1d(a,b)
print(c)

[2 4]


**Problem 10**

From array a remove all items present in array b

In [45]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
ab= np.setdiff1d(a,b)
print(ab)

[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [54]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
results = np.where(a==b)
result = np.where(a==b)[0]

print(results)
print(result)

(array([1, 3, 5, 7], dtype=int64),)
[1 3 5 7]


**Problem 12** 

Get all items between 5 and 10 from a.

In [6]:
#a = np.array([2, 6, 1, 9, 10, 3, 27])
#result= np.a
#print(result)



**Problem 13**

Swap columns 1 and 2 in the array arr.

In [38]:
arr = np.arange(9).reshape(3,3)
a = arr[:, [0,1,2]] = arr[:, [1,0,2]]
print(a)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [42]:
arr = np.arange(9).reshape(3,3)
b = arr[[0,1,2],:] = arr[[1,0,2] ,:]
print(b)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [ ]:
arr = np.arange(9).reshape(3,3)

**Problem 16**

Reverse the columns of a 2D array arr.

In [78]:
arr = np.arange(9).reshape(3,3)
r= arr=[:, ::-1]
print(r)

SyntaxError: invalid syntax (3456379143.py, line 2)

**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [71]:
import random
arr_2d = np.random.randint(5,10, size=(5,3))
print(arr_2d)

[[5 8 7]
 [7 7 8]
 [7 6 7]
 [5 7 6]
 [7 9 7]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [74]:
rand_arr =np.random.rand(5,5)
np.set_printoptions(precision=3)
print(rand_arr)

[[0.352 0.21  0.212 0.125 0.929]
 [0.592 0.35  0.606 0.701 0.669]
 [0.647 0.661 0.047 0.652 0.569]
 [0.453 0.339 0.512 0.838 0.552]
 [0.972 0.201 0.731 0.714 0.417]]
